---
title: "CBI3-C2 Analyse data and report on the use of specific measurements (particularly in terms of reproducibility, bias, specicifity and sensitivity) in the context of bioinformatics"
output: html_notebook
---

During my placement in Ophthalmic Electrophysiology at STH, I had the opportunity to have a PERG test carried out. A silver electrode thread was dropped into the bottom of my eye and attached to electrodes designed to capture electrical signals induced whilst staring at a flickering checkerboard visual stimulus. The raw data was collected by blah. 
Below is an analysis carried out on my raw PERG data. It was carried out using the statistical programming package, R. 

Below is a description of the process carried out to analyse the data

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
